### ISSUE TITLE
Flask-Styleguide generator

### ISSUE THREAD

**Issue by vitalk** [davidhund/styleguide-generators#17]
The Flask-Styleguide extension provides an easy way to automatically generate living style guide for [Flask](http://flask.pocoo.org/) application from [KSS documentation](http://warpspire.com/kss/):

- [Source](https://github.com/vitalk/flask-styleguide)
- [Demo](https://vitalk.github.io/flask-styleguide-example)
- [Documentation](http://flask-styleguide.readthedocs.org/en/latest/)

I can submit a pull request if you are interested.

**Comment by davidhund** [comment]
Hey @vitalk, thanks. I like it, you can get your own ‘Python’ section too :lollipop: 
If you don't mind: make a PR and I'll merge :rocket:
