### ISSUE TITLE
Link redirects to malicious site

### ISSUE THREAD

**Issue by bexux** [davidhund/styleguide-generators#26]
I believe it was StyleDocco or Kalei links that redirects a few times to a storm-bugs-effect.in site with malicious pop-ups. Bad link.

**Comment by davidhund** [comment]
@bexux - Thanks Rebecca, I'll take a look!

**Comment by davidhund** [comment]
@bexux - I remove Kalei Rebeccah, it indeed pointed to a spam domain (though not the storm-bugs site you mentioned). Thanks for letting me know!
