### ISSUE TITLE
Add Runway

### ISSUE THREAD

**Issue by mattrothenberg** [davidhund/styleguide-generators#32]
Hi @davidhund! 

Would it be possible to add a tool that I've been working on, [Runway](http://runway-app.cfapps.io/)?

I'm billing it as "styleguides as a service," as it's really intended for Designers who want a beautiful styleguide, but don't have the facility or time to use a tool like Hologram. 

Thanks!

**Edit**

I should clarify: this isn't about self-promotion as much as it seems like a valuable way to garner feedback about how (if?) this tool could be valuable for designers.

**Comment by davidhund** [comment]
Hey @mattrothenberg 

Thanks for your message. You are always free to PR adding your service.

As for feedback: I think it's actually a very interesting idea!
People (designers, FED's) could even easily generate *one-off* styleguides to sell the idea to management.

The current site does leave me with some questions:

- Pricing?
- Can I generate multiple SG's? Manage (re-build) them?
- Can I *download* my generated styleguide(s) or does it remain online: (& if so: if I re-generate it, does the public URL change?)
- A little Documentation would be great: what syntax is possible/used. Simple KSS-style? Custom?
- One oft-requested feature is better 'sections'. As I can see: currently Runway simply lists all classes and does not group/order them?
- How about pre-processed CSS? Does Runway handle Sass, .scss, or .less files? Custom comments?
- ...

Again: I think it's a very interesting idea (styleguides-as-a-service) and would happily add it to the list (accept a PR). I do think it would be great if your marketing-page could answer some of the above questions.

🖖🏻

**Comment by mattrothenberg** [comment]
@davidhund This is incredibly helpful feedback. Thank you!

I will most certainly make a PR after we answer some of those questions with our next release.

**Comment by davidhund** [comment]
:shipit:
