### ISSUE TITLE
storybook

### ISSUE THREAD

**Issue by longility** [davidhund/styleguide-generators#52]
@davidhund Have you seen [Storybook](https://github.com/storybooks/storybook)?

**Comment by davidhund** [comment]
@longility I have and actually thought it was on the list 😅

If you want a PR is much appreciated. Otherwise I'll add it myself some time.

Thanks

**Comment by longility** [comment]
@davidhund I'm happy to do it. I'm just now wondering where to put it as it covers react, react-native, vue, and angular. I'm guessing other? What are your thoughts?

**Comment by davidhund** [comment]
@longility - Great. Good question: I believe Storybook was only React when I last looked at it. Anyhow: maybe we could introduce another category 'Multiple' and add the tech below as 'tags'?

**Comment by longility** [comment]
@davidhund Okay, when I have time this week. I'll try it out and see how that feels and what that looks like.

**Comment by ndelangen** [comment]
Quite a coincidence I stumbled upon this list 😆
