### ISSUE TITLE
Survival Kit listing.

### ISSUE THREAD

**Issue by RobertinoValue** [davidhund/styleguide-generators#7]
Just a for your info.
The [Survival Kit listed under Other](https://github.com/davidhund/styleguide-generators#other) was superseded by [Snugug+Team Sass's Generator Style Prototype](https://github.com/codingdesigner/Survival-Kit/issues/9#issuecomment-26356982).
Which in turn is now superseded by (it redirects to) [Snugug's North Generator Style Prototype](https://github.com/north/generator-style-prototype)

**Comment by davidhund** [comment]
Ah, I'll update it, thanks!

**Comment by davidhund** [comment]
Thanks @RobertinoValue — I've updated the README

**Comment by RobertinoValue** [comment]
Thanks for the update.
And apologies for the late response.
